### ISSUE TITLE
PSGrafana.psm1 empty message during Import

### ISSUE THREAD

**Issue by chubbbb** [steviecoaster/PSGrafana#26]
Hi Stevie
I'd like to try your module and got error when importing using option 1:
> Import-Module ./PSGrafana.psd1
PSGrafana.psm1 cannot be loaded because its content could not be read. 

PSGrafana.psm1 has zero size
Could you pelase help tk check it? 
Thanks

**Comment by steviecoaster** [comment]
Hey chubbb,

If you'd done a `git clone` on this repo, you'll need to execute the build script in order for things to "work" The psm1 is generated as part of the Azure Pipeline this repo runs against.
